layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: C++
    web_url: https://github.com/topics/cplusplus
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/cpp/cpp.png

  - name: Artificial Intelligence
    web_url: https://github.com/topics/artificial-intelligence
    image_url: https://www.bookmark.com/assets/images/ai/ai.png

  - name: Data Science
    web_url: hhttps://github.com/topics/data-science
    image_url: https://cdn.iconscout.com/icon/free/png-256/data-science-46-1170621.png

  - name: JavaScript
    web_url: https://github.com/topics/js
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png
